# ML Monitoring Configuration for IPO Valuation Platform

# Model Performance Monitoring
model_monitoring:
  prediction_drift_detection:
    enable: true
    thresholds:
      categorical_drift: 0.15
      numerical_drift: 0.10
      prediction_drift: 0.20
    monitoring_window: "24h"
    baseline_window: "30d"
    alert_channels:
      - email
      - slack
      - pagerduty
      
  data_drift_detection:
    enable: true
    statistical_tests:
      - "kolmogorov_smirnov"
      - "chi_square" 
      - "population_stability_index"
    thresholds:
      ks_test_pvalue: 0.05
      chi_square_pvalue: 0.05
      psi_threshold: 0.10
    features_to_monitor:
      financial_models:
        - "revenue_growth_rate"
        - "ebitda_margin"
        - "debt_to_equity"
        - "current_ratio"
        - "beta"
        - "market_cap"
      market_models:
        - "market_volatility"
        - "sector_performance"
        - "interest_rates"
        - "economic_indicators"
      risk_models:
        - "risk_score"
        - "compliance_indicators"
        - "regulatory_mentions"

  model_performance_tracking:
    metrics:
      regression_models:
        - "mean_absolute_error"
        - "mean_squared_error"
        - "r2_score"
        - "mean_absolute_percentage_error"
      classification_models:
        - "accuracy"
        - "precision"
        - "recall"
        - "f1_score"
        - "auc_roc"
      time_series_models:
        - "mean_forecast_error"
        - "mean_absolute_scaled_error"
        - "directional_accuracy"
    
    performance_thresholds:
      dcf_prediction:
        r2_score_min: 0.80
        mae_max: 1000000  # $1M
        mape_max: 0.15    # 15%
      risk_classification:
        accuracy_min: 0.85
        precision_min: 0.80
        recall_min: 0.80
      market_forecast:
        mae_max: 0.05     # 5%
        directional_accuracy_min: 0.65

  explanation_monitoring:
    enable: true
    explanation_drift_threshold: 0.20
    feature_importance_stability: 0.15
    explanation_quality_metrics:
      - "explanation_consistency"
      - "feature_attribution_stability"
      - "counterfactual_validity"

# Infrastructure Monitoring
infrastructure_monitoring:
  endpoint_health:
    health_check_interval: "30s"
    timeout: "10s"
    failure_threshold: 3
    recovery_threshold: 2
    
  performance_metrics:
    latency:
      p50_threshold_ms: 500
      p95_threshold_ms: 1000
      p99_threshold_ms: 2000
    throughput:
      min_qps: 10
      max_qps: 1000
    error_rate:
      max_error_rate: 0.05  # 5%
      
  resource_utilization:
    cpu_threshold: 0.80
    memory_threshold: 0.85
    disk_threshold: 0.90
    gpu_threshold: 0.85
    
  scaling_policies:
    auto_scaling:
      enable: true
      min_replicas: 2
      max_replicas: 20
      target_cpu_utilization: 70
      scale_up_cooldown: "5m"
      scale_down_cooldown: "10m"

# Data Quality Monitoring  
data_quality:
  input_validation:
    required_fields_check: true
    data_type_validation: true
    range_validation: true
    null_value_threshold: 0.10
    
  feature_validation:
    statistical_validation:
      - "mean_within_bounds"
      - "std_within_bounds"
      - "distribution_similarity"
    business_rule_validation:
      - "financial_ratios_consistency"
      - "temporal_consistency"
      - "cross_feature_correlation"
      
  anomaly_detection:
    enable: true
    methods:
      - "isolation_forest"
      - "one_class_svm"
      - "statistical_outliers"
    anomaly_threshold: 0.05
    alert_on_anomalies: true

# Security Monitoring
security_monitoring:
  access_logging:
    enable: true
    log_level: "INFO"
    include_request_data: false  # PII protection
    retention_days: 90
    
  authentication_monitoring:
    failed_login_threshold: 5
    suspicious_activity_detection: true
    rate_limiting:
      requests_per_minute: 100
      burst_limit: 200
      
  data_privacy:
    pii_detection: true
    data_masking: true
    encryption_verification: true
    gdpr_compliance_check: true

# Business Logic Monitoring
business_monitoring:
  valuation_reasonableness:
    dcf_value_range:
      min_value: 0
      max_multiple_of_revenue: 50
    market_multiple_range:
      pe_ratio_max: 200
      pb_ratio_max: 50
      
  prediction_consistency:
    cross_model_validation: true
    temporal_consistency_check: true
    industry_benchmark_comparison: true
    
  regulatory_compliance:
    sec_filing_requirements: true
    disclosure_completeness: true
    audit_trail_integrity: true

# Alert Configuration
alerting:
  channels:
    email:
      enabled: true
      recipients:
        - "ml-team@company.com"
        - "risk-team@company.com"
        - "compliance@company.com"
      smtp_server: "smtp.company.com"
      
    slack:
      enabled: true
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channels:
        - "#ml-alerts"
        - "#ipo-valuation"
        
    pagerduty:
      enabled: true
      integration_key: "${PAGERDUTY_INTEGRATION_KEY}"
      escalation_policy: "ml-escalation"
      
  alert_levels:
    INFO:
      throttle_minutes: 60
      max_alerts_per_hour: 10
    WARNING:
      throttle_minutes: 30
      max_alerts_per_hour: 20
    CRITICAL:
      throttle_minutes: 5
      max_alerts_per_hour: 100
      immediate_notification: true

# Dashboard Configuration
dashboards:
  model_performance_dashboard:
    refresh_interval: "5m"
    widgets:
      - name: "Prediction Accuracy Trends"
        type: "time_series"
        metrics: ["accuracy", "precision", "recall"]
        time_range: "7d"
        
      - name: "Model Drift Detection"
        type: "heatmap"
        metrics: ["feature_drift", "prediction_drift"]
        time_range: "24h"
        
      - name: "Inference Latency"
        type: "histogram"
        metrics: ["p50_latency", "p95_latency", "p99_latency"]
        time_range: "1h"
        
  business_metrics_dashboard:
    refresh_interval: "15m"
    widgets:
      - name: "Valuation Predictions Distribution"
        type: "histogram"
        time_range: "1d"
        
      - name: "Risk Assessment Trends"
        type: "stacked_area"
        time_range: "30d"
        
      - name: "Document Processing Volume"
        type: "line_chart"
        time_range: "7d"

  infrastructure_dashboard:
    refresh_interval: "1m"
    widgets:
      - name: "System Resource Usage"
        type: "gauge"
        metrics: ["cpu_usage", "memory_usage", "disk_usage"]
        
      - name: "Request Volume and Errors"
        type: "dual_axis"
        time_range: "4h"
        
      - name: "Auto-scaling Events"
        type: "event_timeline"
        time_range: "24h"

# Logging Configuration
logging:
  structured_logging: true
  log_level: "INFO"
  log_format: "json"
  
  log_retention:
    application_logs: "30d"
    access_logs: "90d"
    audit_logs: "7y"  # Regulatory requirement
    error_logs: "1y"
    
  log_sampling:
    enable: true
    sample_rate: 0.1  # 10% sampling for high-volume logs
    always_log_errors: true
    
  sensitive_data_filtering:
    enable: true
    pii_fields: ["ssn", "credit_card", "email", "phone"]
    financial_fields: ["account_number", "routing_number"]

# Audit and Compliance
audit:
  model_lineage_tracking:
    enable: true
    track_data_sources: true
    track_feature_transformations: true
    track_model_versions: true
    
  prediction_audit_trail:
    enable: true
    log_all_predictions: false  # Only for high-value predictions
    log_explanation_data: true
    retention_period: "7y"
    
  compliance_reporting:
    automated_reports:
      - name: "Model Performance Report"
        frequency: "weekly"
        recipients: ["compliance@company.com"]
        
      - name: "Data Quality Report"
        frequency: "daily"
        recipients: ["data-team@company.com"]
        
      - name: "Security Audit Report"
        frequency: "monthly"
        recipients: ["security@company.com"]

# Experimental Features
experimental:
  advanced_explainability:
    enable: false
    methods: ["lime", "shap", "integrated_gradients"]
    
  fairness_monitoring:
    enable: false
    protected_attributes: ["geography", "company_size"]
    fairness_metrics: ["demographic_parity", "equalized_odds"]
    
  continuous_learning:
    enable: false
    retrain_threshold: 0.05  # Retrain if performance drops 5%
    automatic_deployment: false  # Manual approval required

# Integration Settings
integrations:
  vertex_ai_monitoring:
    enable: true
    project_id: "${GCP_PROJECT_ID}"
    region: "us-central1"
    
  bigquery_logging:
    enable: true
    dataset: "ml_monitoring"
    tables:
      predictions: "prediction_logs"
      model_metrics: "model_performance"
      data_quality: "data_quality_metrics"
      
  cloud_monitoring:
    enable: true
    custom_metrics_prefix: "ipo_valuation/"
    
  tensorflow_data_validation:
    enable: true
    schema_validation: true
    anomaly_detection: true